### ISSUE TITLE
[Backstage] invalid app bundle schema

### ISSUE THREAD

**Issue by phac008** [suxess-it/kubriX#85]
after build and upload backstage image receiving following error on startup;

(local test with yarn dev work properly)
.....

`/opt/app-root/src/node_modules/@backstage/backend-app-api/dist/index.cjs.js:1806
          throw new errors.ForwardedError(
                ^
ForwardedError: Plugin 'app' startup failed; caused by Error: Invalid app bundle schema. If this error is unexpected you need to run `yarn build` in the app. If that doesn't help you should make sure your config schema is correct and rebuild the app bundle again. Caused by the following schema error, Error: Config validation failed, Config must have required property 'fractionDigits' { missingProperty=fractionDigits } at /kubecost; Config must have required property 'unitprefix' { missingProperty=unitprefix } at /kubecost
    at /opt/app-root/src/node_modules/@backstage/backend-app-api/dist/index.cjs.js:1806:17
    at async /opt/app-root/src/node_modules/@backstage/backend-app-api/dist/index.cjs.js:1805:9
    ... 3 lines matching cause stack trace ...
    at async BackstageBackend.start (/opt/app-root/src/node_modules/@backstage/backend-app-api/dist/index.cjs.js:1894:5) {
  cause: Error: Invalid app bundle schema. If this error is unexpected you need to run `yarn build` in the app. If that doesn't help you should make sure your config schema is correct and rebuild the app bundle again. Caused by the following schema error, Error: Config validation failed, Config must have required property 'fractionDigits' { missingProperty=fractionDigits } at /kubecost; Config must have required property 'unitprefix' { missingProperty=unitprefix } at /kubecost
      at readConfigs (/opt/app-root/src/node_modules/@backstage/plugin-app-backend/dist/cjs/router-B9fabz1o.cjs.js:70:13)
      at async Object.createRouter (/opt/app-root/src/node_modules/@backstage/plugin-app-backend/dist/cjs/router-B9fabz1o.cjs.js:272:56)
      at async Object.init [as func] (/opt/app-root/src/node_modules/@backstage/plugin-app-backend/dist/alpha.cjs.js:57:26)
      at async /opt/app-root/src/node_modules/@backstage/backend-app-api/dist/index.cjs.js:1805:9
      at async Promise.all (index 0)
      at async BackendInitializer.doStart_fn (/opt/app-root/src/node_modules/@backstage/backend-app-api/dist/index.cjs.js:1766:3)
      at async BackendInitializer.start (/opt/app-root/src/node_modules/@backstage/backend-app-api/dist/index.cjs.js:1626:5)
      at async BackstageBackend.start (/opt/app-root/src/node_modules/@backstage/backend-app-api/dist/index.cjs.js:1894:5)
}
Node.js v18.19.1`

**Comment by jkleinlercher** [comment]
@phac008 is this issue still valid or can we close it?
